### ISSUE TITLE
Lazy loading not working until scroll

### ISSUE THREAD

**Issue by MatanYed** [paveisistemas/ionic-image-lazy-load#21]
I have 2 pages:
- Feed of songs
- Song page

In feed, the lazy loading working good, then I go to song page, and the lazy loading not working until I scroll. I tried ionicScrollDellegate.resize() - not helping.
It's happenes only on the device, on pc it's ok.

Video:
https://drive.google.com/file/d/0B_2AM8ZhXhE9Zk5aMlRyalplYUk/view

**Comment by MatanYed** [comment]
I fixed it somehow. I just wrote there again (deleted code and wrote again).

**Comment by daggeto** [comment]
Same issue here. MatanYed solutions doesn't help.

**Comment by bamarni** [comment]
For me no image is shown until I touch the screen, I can wait 30 seconds and nothing will show, then as soon as I touch the screen they start loading and showing... Any idea why?
