### ISSUE TITLE
Console logging

### ISSUE THREAD

**Issue by renekorss** [paveisistemas/ionic-image-lazy-load#27]
Could you please remove `console.log` lines? At least for production.

https://github.com/paveisistemas/ionic-image-lazy-load/blob/master/ionic-image-lazy-load.js#L69
and
https://github.com/paveisistemas/ionic-image-lazy-load/blob/master/ionic-image-lazy-load.js#L84

**Comment by somtam** [comment]
Hello,
I have the same problem. I want to deploy my app but i don't know if this could be a problem.
Thanks for support!

**Comment by renekorss** [comment]
@somtam It won't be a problem, but it just pollutes console if developing. Hard to find your own logged info.

**Comment by somtam** [comment]
Yes thanks,
and it comes also in mind that I have to take of the cordova-plugin-console plugin before deploy to production.

**Comment by somtam** [comment]
Anyway, also for the development side it would be better to not have that log.
