### ISSUE TITLE
Adding 'ionicLazyLoad' to module, blank page

### ISSUE THREAD

**Issue by celiostat** [paveisistemas/ionic-image-lazy-load#6]
Hi, 
after downloading the ionic-image-lazy-load.js file, and adding the correct path in my index HTML(	<script src="js/ionic-image-lazy-load.js"></script>) , 
when adding the 'ionicLazyLoad'  to my app.js module, in auto refresh my app suddently becomes ...a white screen, have you got any idea on what is going wrong ? 

Thanks, 
Laurent

**Comment by pavei** [comment]
Did you solved?
