### ISSUE TITLE
Features pull request proposition

### ISSUE THREAD

**Issue by mvidailhet** [paveisistemas/ionic-image-lazy-load#8]
Hello,

I really liked your directive and it helped me a lot! I actually needed some more features, so I added it to your code.

Features I've added:
- Possibility to have a ionic spinner while the image load (#1)
- Added 2 parameters to specify a distance from the bottom and right of the screen where the image will start loading (#5)
- Possibility to use a background-image instead of an image element.

Let me now if you're interested by a pull-request. I will be happy to talk about the changes with you.

**Comment by pavei** [comment]
Please submit a pull-request!

**Comment by mvidailhet** [comment]
I'm trying to push my branch but I get a permission denied.

**Comment by mvidailhet** [comment]
Never mind, I forgot to fork first :)

**Comment by pavei** [comment]
Thanks a lot :D

**Comment by pavei** [comment]
If you can, please update readme too, adding a exemple of your new features :D

**Comment by mvidailhet** [comment]
Of course! I've sent the pull request.

Thanks again for this great directive Pavei. It helped me a lot!

**Comment by mvidailhet** [comment]
I found a bug in my code preventing image to load properly on img elements. I created another pull request.

I also made an updated Codepen of your directive usage with the new features, feel free to update the link on your Github :) : http://codepen.io/mvidailhet/pen/yNOGzY
